### ISSUE TITLE
List members of PDS 

### ISSUE THREAD

**Issue by dogboydog** [IBM/zos-node-accessor#14]
Hi,

It would be nice to have an API to list members of a PDS, with attributes like Lrecl, Recfm etc. 

A command to do this is documented in the below pdf on page 180 (204 of PDF) 

I also was wondering if this package sets ISPFStats to true -- I didn't see it in the code -- I just saw this on page 97 (121 of the PDF). Not a big deal though just might be nice to automatically update statistics when you read and write members 

https://www-304.ibm.com/servers/resourcelink/svc00100.nsf/pages/zosv2r3sc273662/$file/halu001_v2r3.pdf

**Comment by polyrabbit** [comment]
Hello again, we just released version 1.0.0, which supports listing PDS members. Currently we reused api `listDataset`, and made it able to parse PDS member response. So in order to list members, you can call `listDataset('HLQ.ABC(*)')`

Also, the `ISPFStats` flag is set now, thanks for your reminding!

**Comment by polyrabbit** [comment]
Closing as this requirement is done.
